package com.lanouteam.dllo.mirror.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ADMIN".
 */
public class Admin {

    private String name;
    private String token;
    private String uid;

    public Admin() {
    }

    public Admin(String name, String token, String uid) {
        this.name = name;
        this.token = token;
        this.uid = uid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

}
