package com.lanouteam.dllo.mirror.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lanouteam.dllo.mirror.db.Admin;

import com.lanouteam.dllo.mirror.db.AdminDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adminDaoConfig;

    private final AdminDao adminDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adminDaoConfig = daoConfigMap.get(AdminDao.class).clone();
        adminDaoConfig.initIdentityScope(type);

        adminDao = new AdminDao(adminDaoConfig, this);

        registerDao(Admin.class, adminDao);
    }
    
    public void clear() {
        adminDaoConfig.getIdentityScope().clear();
    }

    public AdminDao getAdminDao() {
        return adminDao;
    }

}
